# Generated by Django 5.0.9 on 2024-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='breed')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
            },
        ),
    ]
