# Generated by Django 5.0.9 on 2024-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=25, unique=True, verbose_name='URL'),
        ),
    ]
